apiVersion: v1
kind: Service
metadata:
  name: fundamentals-api
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: fundamentals-api
  ports:
    - name: http
      port: 8011
      targetPort: 8011
      protocol: TCP
