import type { Logger } from '@trader/core';
import type { StrategyOutput } from '@trader/shared-types';
import type { CycleBatch } from '../CycleAnalysisBatcher.ts';
import type {
    ReportContext, SanityFlag, StrategyRenderer, TelemetryBlock,
} from '../ReportContext.ts';
import {
    buildNarrative, escapeHtml, formatWindowLabel, type NarrativeLLM,
} from './utils.ts';

// Renderer for sector_momentum_v1. The strategy ranks tickers by sector-relative
// momentum (cum_return − sector_mean), z-scored across the universe. The reporting
// questions:
//   - What were the sector means this cycle? (table)
//   - For each pick, how does sector-adjusted vs raw momentum compare? (table)
//   - Is the strategy degenerated by missing-sector coverage? (banner)
//
// Strategy-specific sanity rules:
//   SECTOR_DATA_MISSING            — unknown-sector fraction > 0.5 (critical: strategy
//                                    degenerates to plain momentum)
//   SECTOR_CONCENTRATION_OVERFLOW  — any sector has > MAX_SECTOR_FRACTION of picks
//                                    (warn: portfolio-level over-concentration)
const UNKNOWN_SECTOR_CRITICAL = 0.5;
const MAX_SECTOR_FRACTION     = 0.5;

export class SectorMomentumRenderer implements StrategyRenderer {
    readonly strategyId = 'sector_momentum_v1';

    constructor(
        private readonly llm: NarrativeLLM,
        private readonly logger: Logger,
    ) {}

    async build(batch: CycleBatch, telemetry: TelemetryBlock, sanity: SanityFlag[]): Promise<ReportContext> {
        const head = batch.signals[0]?.features_snapshot;
        const extraFlags = head ? this.strategyRules(head, batch) : [];
        const allFlags   = [...sanity, ...extraFlags];

        const windowLabel = formatWindowLabel(batch);
        const sectionsHtml = head
            ? renderSectorMomentumSections(batch, head, telemetry)
            : `<p style="color:#888;font-style:italic">No features_snapshot — sector-momentum sections unavailable.</p>`;

        let narrative: string;
        try {
            narrative = await buildNarrative(this.llm, {
                strategyId: batch.strategyId,
                windowLabel, batch, telemetry, sanity: allFlags,
                extraContext: head ? sectorContextString(batch, head, telemetry) : undefined,
            });
        } catch (err) {
            this.logger.warn({ err, cycleKey: batch.cycleKey }, 'sector-momentum-renderer: narrative LLM failed; falling back to template');
            narrative = `Sector-momentum cycle ${batch.strategyId} produced ${telemetry.signals.total} action(s).`;
        }

        return {
            strategyId: batch.strategyId,
            windowLabel, telemetry,
            sanity: allFlags,
            narrative,
            sectionsHtml,
        };
    }

    strategyRules(head: StrategyOutput, batch: CycleBatch): SanityFlag[] {
        const out: SanityFlag[] = [];

        // SECTOR_DATA_MISSING — strategy degenerates when more than half the universe
        // maps to 'Unknown'. The strategy itself stamps `degraded_unknown_sectors` into
        // every per-ticker attribution row when it detects this, so we prefer that
        // signal when present; fall back to recomputing from the sectors map.
        const sectors = head.sectors ?? {};
        const tickers = Object.keys(sectors);
        const degradedFlagFromStrategy = firstNonZero(
            Object.values(head.factor_attributions ?? {}).map((row) => row.degraded_unknown_sectors ?? 0),
        );
        const unknownFraction = degradedFlagFromStrategy ?? (tickers.length === 0
            ? 0
            : tickers.filter((t) => (sectors[t] ?? 'Unknown') === 'Unknown').length / tickers.length);
        if (unknownFraction > UNKNOWN_SECTOR_CRITICAL) {
            out.push({
                severity: 'critical',
                code: 'SECTOR_DATA_MISSING',
                message: `${(unknownFraction * 100).toFixed(0)}% of the universe has sector='Unknown' — sector-relative ranking degenerates to plain momentum.`,
                hint: 'Re-run UniverseManager sector enrichment or check the YahooSectorClient logs for upstream failures.',
                evidence: { unknownFraction },
            });
        }

        // SECTOR_CONCENTRATION_OVERFLOW — any single sector represents more than
        // MAX_SECTOR_FRACTION of the cycle's picks (sector-relative momentum is meant to
        // *diversify* across sectors, not concentrate inside one).
        if (batch.signals.length > 0) {
            const counts = new Map<string, number>();
            for (const s of batch.signals) {
                const sec = sectors[s.ticker] ?? 'Unknown';
                counts.set(sec, (counts.get(sec) ?? 0) + 1);
            }
            for (const [sec, n] of counts) {
                const fraction = n / batch.signals.length;
                if (fraction > MAX_SECTOR_FRACTION) {
                    out.push({
                        severity: 'warn',
                        code: 'SECTOR_CONCENTRATION_OVERFLOW',
                        message: `Sector "${sec}" holds ${n}/${batch.signals.length} picks (${(fraction*100).toFixed(0)}% > ${MAX_SECTOR_FRACTION*100}%).`,
                        hint: 'Sector-relative momentum should spread picks across sectors; concentration suggests sector means or z-scoring are degenerate.',
                        evidence: { sector: sec, n, fraction },
                    });
                    // Don't break — emit one flag per offending sector.
                }
            }
        }

        return out;
    }
}

// ── HTML sections ─────────────────────────────────────────────────────────

function renderSectorMomentumSections(batch: CycleBatch, head: StrategyOutput, t: TelemetryBlock): string {
    return [
        renderSectorCoverageBanner(t),
        renderSectorMeansTable(head),
        renderPerPickAdjustedTable(batch, head),
    ].filter(Boolean).join('\n');
}

function renderSectorCoverageBanner(t: TelemetryBlock): string {
    const f = t.universe.unknownSectorFraction;
    if (f <= 0.3) return '';
    const color = f > 0.5 ? '#c0392b' : '#b58900';
    return `
    <div style="margin:14px 0;border-left:4px solid ${color};padding:8px 12px;background:#fafafa">
        <b style="color:${color};text-transform:uppercase;font-size:11px">Sector coverage degraded</b>
        <div style="font-size:13px">${(f * 100).toFixed(0)}% of the universe carries sector='Unknown'. Sector-relative ranking is unreliable until coverage improves.</div>
    </div>`;
}

function renderSectorMeansTable(head: StrategyOutput): string {
    const attr = head.factor_attributions ?? {};
    const sectors = head.sectors ?? {};
    // Reconstruct per-sector means from the per-ticker raw momentum + the sector tag.
    // (The strategy doesn't ship sector_means on the output; reconstructing here keeps
    // the renderer self-contained without changing the dataclass shape.)
    const bySector = new Map<string, { sum: number; n: number }>();
    for (const [t, row] of Object.entries(attr)) {
        const sec = sectors[t] ?? 'Unknown';
        const raw = row.momentum ?? 0;
        const entry = bySector.get(sec) ?? { sum: 0, n: 0 };
        entry.sum += raw; entry.n += 1;
        bySector.set(sec, entry);
    }
    if (bySector.size === 0) return '';
    const rows = Array.from(bySector.entries())
        .map(([sec, e]) => ({ sec, n: e.n, mean: e.n > 0 ? e.sum / e.n : 0 }))
        .sort((a, b) => b.mean - a.mean)
        .map((r) => `<tr><td>${escapeHtml(r.sec)}</td><td style="text-align:right">${r.n}</td><td style="text-align:right">${r.mean.toFixed(4)}</td></tr>`)
        .join('');
    return `
    <div style="margin:14px 0">
        <h3 style="margin:0 0 6px 0;font-size:14px">Sector means (cum return)</h3>
        <table cellpadding="4" style="border-collapse:collapse;font-size:12px">
            <thead><tr style="background:#fafafa"><th align="left">Sector</th><th align="right">n</th><th align="right">mean cum_return</th></tr></thead>
            <tbody>${rows}</tbody>
        </table>
    </div>`;
}

function renderPerPickAdjustedTable(batch: CycleBatch, head: StrategyOutput): string {
    const attr = head.factor_attributions ?? {};
    const sectors = head.sectors ?? {};
    const rows = batch.signals.map((s) => {
        const row = attr[s.ticker] ?? {};
        const raw = row.momentum         ?? 0;
        const adj = row.sector_momentum  ?? 0;
        const sec = sectors[s.ticker]    ?? 'Unknown';
        return `<tr>
            <td>${escapeHtml(s.ticker)}</td>
            <td>${escapeHtml(sec)}</td>
            <td style="text-align:right">${raw.toFixed(4)}</td>
            <td style="text-align:right"><b>${adj.toFixed(4)}</b></td>
        </tr>`;
    }).join('');
    return `
    <div style="margin:14px 0">
        <h3 style="margin:0 0 6px 0;font-size:14px">Per-pick: raw vs sector-adjusted</h3>
        <table cellpadding="4" style="border-collapse:collapse;font-size:12px">
            <thead><tr style="background:#fafafa"><th align="left">Ticker</th><th>Sector</th><th align="right">raw momentum</th><th align="right">sector-adj (composite)</th></tr></thead>
            <tbody>${rows}</tbody>
        </table>
    </div>`;
}

// ── Helpers ──────────────────────────────────────────────────────────────

function sectorContextString(batch: CycleBatch, head: StrategyOutput, t: TelemetryBlock): string {
    const sectors = head.sectors ?? {};
    const sectorsForPicks = batch.signals.map((s) => sectors[s.ticker] ?? 'Unknown');
    const distinct = new Set(sectorsForPicks);
    return [
        `Unknown sector fraction across universe: ${(t.universe.unknownSectorFraction * 100).toFixed(1)}%`,
        `Picks span ${distinct.size} sector(s): ${Array.from(distinct).join(', ')}`,
    ].join('. ');
}

function firstNonZero(xs: number[]): number | null {
    for (const v of xs) if (v && v !== 0) return v;
    return null;
}
