apiVersion: v1
kind: Service
metadata:
  name: fundamentals-ingestion
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: fundamentals-ingestion
  ports:
    - name: http
      port: 8010
      targetPort: 8010
      protocol: TCP
