apiVersion: v1
kind: Service
metadata:
  name: trading-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: trading-service
  ports:
    - port: 3005
      targetPort: 3005
      protocol: TCP
