apiVersion: v1
kind: Service
metadata:
  name: signal-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: signal-service
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
