apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: portfolio-service
  ports:
    - port: 3006
      targetPort: 3006
      protocol: TCP
