apiVersion: v1
kind: Service
metadata:
  name: strategy-engine
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: strategy-engine
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
