apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-web
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: trader.local
      http:
        paths:
          - path: /portal-api
            pathType: Prefix
            backend:
              service:
                name: frontend-web
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-web
                port:
                  number: 3000
