apiVersion: v1
kind: Service
metadata:
  name: market-data-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: market-data-service
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
